services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CRA_POSTGRES_DB}
      POSTGRES_USER: ${CRA_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CRA_POSTGRES_PASS}
    ports:
      - ${CRA_POSTGRES_PORT}:5432
    volumes:
      - cra-pg-data:/var/lib/postgresql/data:rw

  app:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      CRA_POSTGRES_HOST: db
      CRA_POSTGRES_PORT: 5432
      CRA_POSTGRES_DB: ${CRA_POSTGRES_DB}
      CRA_POSTGRES_USER: ${CRA_POSTGRES_USER}
      CRA_POSTGRES_PASS: ${CRA_POSTGRES_PASS}
      CRA_ADMIN_USERNAME: ${CRA_ADMIN_USERNAME}
      CRA_ADMIN_PASSWORD: ${CRA_ADMIN_PASSWORD}
      CRA_JWT_SECRET: ${CRA_JWT_SECRET}
    ports:
      - ${CRA_APP_PORT}:8080

volumes:
  cra-pg-data:
