spring:
  application:
    name: clinical-registry-api

  profiles:
    active: prod

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    placeholders:
      admin_username: ${spring.security.user.name}
      admin_password: ${spring.security.user.password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: ${CRA_ADMIN_USERNAME}
      password: ${CRA_ADMIN_PASSWORD}

jwt:
  secret: ${CRA_JWT_SECRET}
