spring:
  profiles.active: prod
  security.user:
    name: ${CRA_ADMIN_USERNAME}
    password: ${CRA_ADMIN_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update

jwt.secret: ${CRA_JWT_SECRET}

