spring:
  application:
    name: clinical-registry-api

  security:
    user:
      name: ${CRA_ADMIN_USERNAME}
      password: ${CRA_ADMIN_PASSWORD}

  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    placeholders:
      admin_username: ${spring.security.user.name}
      admin_password: ${spring.security.user.password}

  profiles:
    active: prod

jwt:
  secret: ${CRA_JWT_SECRET}
