INSERT INTO ROLE (NAME) VALUES ('ADMIN');
INSERT INTO ROLE (NAME) VALUES ('DIRECTOR');
INSERT INTO ROLE (NAME) VALUES ('DOCTOR');
INSERT INTO ROLE (NAME) VALUES ('NURSE');
INSERT INTO ROLE (NAME) VALUES ('ASSISTANT');
INSERT INTO ROLE (NAME) VALUES ('PATIENT');
